version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: weather-history-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - weather-history-network

networks:
  weather-history-network:
    driver: bridge