AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x

Parameters:
  NotificationEmail:
    Type: String
    Default: ""
  DLQQueueUrl:
    Type: String
    Default: ""

Resources:
  DLQProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/handler.handler
      MemorySize: 128
      Environment:
        Variables:
          NOTIFICATION_EMAIL: !Ref NotificationEmail
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: "*"
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref DLQQueueUrl
            BatchSize: 1

Outputs:
  DLQProcessorFunctionArn:
    Description: DLQ Processor Lambda Function ARN
    Value: !GetAtt DLQProcessorFunction.Arn
